name = "finance-tracker"
pages_build_output_dir = "public"
compatibility_date = "2024-05-12"

# Bind the D1 database
[[d1_databases]]
binding = "DB" # The variable name used in your functions, e.g. env.DB
database_name = "finance_db" # The name of your database in Cloudflare
database_id = "24d058e6-81c5-4d30-8efc-2154b35c7731" # The name of your database in Cloudflare

# Define environment variables (like Google Sheet ID)
[vars]
GOOGLE_SHEET_ID = "1bf-IQV-9LAUYwLKxcWpTUEVMzpURG9K9T1FJtZkTG40"

# Note: GOOGLE_SERVICE_ACCOUNT_JSON should be added as a Secret in Cloudflare dashboard,
# not stored in plain text here.
